import type { InferSelectModel } from "drizzle-orm";
import { jobPlatforms, jobs } from "../drizzle/schema";

export type SamplePlatform = InferSelectModel<typeof jobPlatforms>;
export type SampleJob = InferSelectModel<typeof jobs>;

const now = Date.now();

export const samplePlatforms: SamplePlatform[] = [
  { id: 1, name: "FlexJobs", url: "https://www.flexjobs.com/", tier: "tier1", category: "General", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 2, name: "We Work Remotely", url: "https://weworkremotely.com/", tier: "tier1", category: "General", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 3, name: "Remote.co", url: "https://remote.co/", tier: "tier1", category: "General", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 4, name: "RemoteOK", url: "https://remoteok.com/", tier: "tier1", category: "General", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 5, name: "LinkedIn Jobs", url: "https://www.linkedin.com/jobs/", tier: "tier1", category: "General", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 6, name: "Remotive", url: "https://remotive.com/", tier: "tier2", category: "General", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 7, name: "Arc", url: "https://arc.dev/", tier: "tier3", category: "Tech", isActive: 1, lastScraped: null, createdAt: new Date(now) },
  { id: 8, name: "PowerToFly", url: "https://powertofly.com/", tier: "tier4", category: "Diversity", isActive: 1, lastScraped: null, createdAt: new Date(now) },
];
export const sampleJobs: SampleJob[] = [
  {
    id: 1,
    externalId: "sample-senior-fullstack",
    title: "Senior Full Stack Developer",
    company: "TechFlow Inc",
    description: "Build scalable remote-first web applications using React, Node.js, PostgreSQL, Docker, and AWS.",
    requirements: "5+ years JavaScript or TypeScript, React, Node.js, SQL, REST APIs, Git",
    responsibilities: "Own core product surfaces, improve platform reliability, and mentor engineers.",
    benefits: "Health insurance, 401k matching, unlimited PTO, remote work, learning budget",
    location: "Remote - Worldwide",
    jobType: "full-time",
    salaryMin: 120000,
    salaryMax: 160000,
    salaryCurrency: "USD",
    skills: "JavaScript, TypeScript, React, Node.js, PostgreSQL, AWS, Docker",
    applicationUrl: "https://boards.greenhouse.io/techflow/jobs/12345",
    applicationEmail: null,
    applicationProcess: "greenhouse",
    platformId: 2,
    sourceUrl: "https://weworkremotely.com/remote-jobs/techflow-senior-full-stack-developer",
    postedDate: new Date(now - 2 * 86400000),
    expiryDate: null,
    isActive: 1,
    visaSponsorshipAvailable: 1,
    openHiringSupport: 0,
    diversityFriendly: 1,
    createdAt: new Date(now - 2 * 86400000),
    updatedAt: new Date(now - 2 * 86400000),
  },
  {
    id: 2,
    externalId: "sample-frontend-engineer",
    title: "Frontend Engineer",
    company: "DesignHub",
    description: "Create accessible product interfaces with React, TypeScript, Tailwind, testing, and design systems.",
    requirements: "3+ years frontend development, strong CSS skills, accessibility knowledge",
    responsibilities: "Ship polished UI, partner with design, and maintain shared components.",
    benefits: "Medical, dental, vision, equity, flexible hours, home office stipend",
    location: "Remote - US Only",
    jobType: "full-time",
    salaryMin: 100000,
    salaryMax: 130000,
    salaryCurrency: "USD",
    skills: "React, TypeScript, CSS, Tailwind, Figma, Accessibility, Testing",
    applicationUrl: "https://jobs.lever.co/designhub/frontend-engineer",
    applicationEmail: null,
    applicationProcess: "lever",
    platformId: 4,
    sourceUrl: "https://remoteok.com/remote-jobs/designhub-frontend-engineer",
    postedDate: new Date(now - 86400000),
    expiryDate: null,
    isActive: 1,
    visaSponsorshipAvailable: 0,
    openHiringSupport: 0,
    diversityFriendly: 1,
    createdAt: new Date(now - 86400000),
    updatedAt: new Date(now - 86400000),
  },
  {
    id: 3,
    externalId: "sample-backend-python",
    title: "Backend Python Developer",
    company: "DataStream Analytics",
    description: "Build data pipelines and APIs with Python, FastAPI, PostgreSQL, Redis, Kafka, Docker, and Kubernetes.",
    requirements: "4+ years Python, FastAPI or Django, PostgreSQL, Redis, message queues",
    responsibilities: "Design APIs, scale event processing, and improve observability.",
    benefits: "Remote-first, 30 days PTO, conference budget, equipment allowance",
    location: "Remote - Europe",
    jobType: "full-time",
    salaryMin: 80000,
    salaryMax: 110000,
    salaryCurrency: "EUR",
    skills: "Python, FastAPI, PostgreSQL, Redis, Kafka, Docker, Kubernetes",
    applicationUrl: "https://datastream.myworkdayjobs.com/careers/job/12345",
    applicationEmail: null,
    applicationProcess: "workday",
    platformId: 6,
    sourceUrl: "https://remotive.com/remote-jobs/software-dev/backend-python-developer",
    postedDate: new Date(now - 3 * 86400000),
    expiryDate: null,
    isActive: 1,
    visaSponsorshipAvailable: 1,
    openHiringSupport: 1,
    diversityFriendly: 1,
    createdAt: new Date(now - 3 * 86400000),
    updatedAt: new Date(now - 3 * 86400000),
  },
  {
    id: 4,
    externalId: "sample-contract-rn",
    title: "Contract React Native Developer",
    company: "MobileFirst Agency",
    description: "Six month remote contract building a new mobile app with React Native, TypeScript, iOS, Android, and REST APIs.",
    requirements: "3+ years React Native, published apps, TypeScript",
    responsibilities: "Build mobile features, integrate APIs, and support release cycles.",
    benefits: "Flexible schedule, remote work, potential full-time conversion",
    location: "Remote - Worldwide",
    jobType: "contract",
    salaryMin: 166400,
    salaryMax: 249600,
    salaryCurrency: "USD",
    skills: "React Native, TypeScript, iOS, Android, REST APIs",
    applicationUrl: "https://mobilefirst.example.com/contract/rn-dev",
    applicationEmail: "hiring@mobilefirst.example.com",
    applicationProcess: "email",
    platformId: 7,
    sourceUrl: "https://arc.dev/remote-jobs/react-native",
    postedDate: new Date(now - 4 * 86400000),
    expiryDate: null,
    isActive: 1,
    visaSponsorshipAvailable: 0,
    openHiringSupport: 0,
    diversityFriendly: 0,
    createdAt: new Date(now - 4 * 86400000),
    updatedAt: new Date(now - 4 * 86400000),
  },
];
